export const ABI = [
    "constructor(address _dev, address _USDT)",
    "event addAmountMade(string eventName, uint256 _amount, uint256 _timestamp, uint256 _endTime)",
    "event addTimeMade(string eventName, uint256 _period, uint256 _timestamp, uint256 _endTime)",
    "event depositMade(string eventName, uint256 _amount, uint256 _timestamp, uint256 _endTime)",
    "event refundMade(string eventName, uint256 _amount, uint256 _timestamp, uint256 _endTime)",
    "event releaseMade(string eventName, uint256 _amount, uint256 _timestamp, uint256 _endTime)",
    "function USDT() view returns (address)",
    "function addAmount(uint256 _amount)",
    "function addTime(uint256 _period)",
    "function amount() view returns (uint256)",
    "function client() view returns (address)",
    "function deposit(uint256 _amount, uint256 _period)",
    "function dev() view returns (address)",
    "function duration() view returns (uint256)",
    "function endTime() view returns (uint256)",
    "function getChainID() view returns (uint256)",
    "function getContractAddress() view returns (address)",
    "function getTokenBalance() view returns (uint256)",
    "function isDepositExecuted() view returns (bool)",
    "function refund()",
    "function release(uint256 _amount)",
    "function startTime() view returns (uint256)",
    "function totalReleasedAmount() view returns (uint256)"
];